### PR TITLE
FEAT: Made the site responsive

### PR DESCRIPTION
**Pull request by VishalPatil18**
### 📝 Description

Made the site completely responsive. 

### 🚀 New behavior

- The site is now completely responsive. 
- Filters button appears on the product listing page which toggles the filters menu

### 🖼 Preview Link

https://viskart-react-version-1uz94w6mt-vishalpatil18.vercel.app/

### 💣 Is this a breaking change?
- [ ] Yes
- [x] No

### 🔬 Is the code self-reviewed?
- [x] Yes
- [ ] No

### 📋 Is the code well-formatted?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by AnkurChunekar** [comment]
vishal pr

- You can Increase font size for the discount text on product cards in cart and wishlist pages.

**Comment by AnkurChunekar** [comment]
vishal pr  2

- This `See all products` on homepage button doesn't navigate user to products page, user has to scroll all the way down just to navigate to products page. You can add a link here.

**Review by AnkurChunekar — APPROVED** [review]
- Other than the suggestions above, everything looks good.
- Site is fully responsive, and filter menu on mobile screen is looks good.
- code is very neat and clean.
- great work @VishalPatil18

**Comment by VishalPatil18** [comment]
> 

Sure will correct this

**Comment by VishalPatil18** [comment]
> vishal pr
> 
>     * You can Increase font size for the discount text on product cards in cart and wishlist pages.

Sure will correct this, Thanks for pointing out!

**Comment by VishalPatil18** [comment]
> vishal pr 2
> 
>     * This `See all products` on homepage button doesn't navigate user to products page, user has to scroll all the way down just to navigate to products page. You can add a link here.

Sure, I will add this...

**Comment by starver20** [comment]
Login from single product is not working. Rest all looks good to merge.

**Review by starver20 — APPROVED** [review]

**Comment by VishalPatil18** [comment]
> Login from single product is not working. Rest all looks good to merge.

Thanks for pointing it out @starver20. For now, I've created the [issue](https://github.com/VishalPatil18/viskart-react-version/issues/28) #28. I will work on this later

**Pull request merged**
