### PR TITLE
FEAT: Update UI of Landing Page, Single Product Page, Cart Page and Wishlist Page

### PR DESCRIPTION
**Pull request by VishalPatil18**
### 📝 Description

Update the UI for the whole website. 

### 🚀 New behavior

- The single product page is updated
- Updated the landing page
- Updated the product card
- Updated Navbar
- Updated Wishlist and Cart Page
- Added Share link feature for a single product
- Added the Shop By Category Section on Landing page which shows only that category products on product listing page when selected

### 🖼 Preview Link

https://viskart-react-version-ideebek5t-vishalpatil18.vercel.app/

### 💣 Is this a breaking change?
- [ ] Yes
- [x] No

### 🔬 Is the code self-reviewed?
- [x] Yes
- [ ] No

### 📋 Is the code well-formatted?
- [x] Yes
- [ ] No

### 🔗 Related to Issue 
- None

### CODE REVIEW

**Review by dipteekhd — APPROVED** [review]
In wish list page
There should be MOVE TO CART option
1.If item not in cart ,move it to cart (working fine)
2.If item already in cart ,move that item in cart and increment quantity of that item(instead of adding GO TO CART option)

**Review by gadgetfather — APPROVED** [review]
UI looks great now.  Sharing functionality is also working perfectly. 
One thing I would like to suggest about the footer is 
You can give footer width: 100%. right now it's centered 

image

## Reason: 
I checked some sites and noticed that if the footer has color then `width:100% ` and on some sites where footer is transparent (without any bg-color) there it is centered. 
## footer with color
On groww they have centered top but footer is full
image
image

## footer ( with no color)
On gatsby, they have a transparent footer.
image

Apart from that great work @VishalPatil18 👍

**Comment by VishalPatil18** [comment]
> In wish list page There should be MOVE TO CART option 1.If item not in cart ,move it to cart (working fine) 2.If item already in cart ,move that item in cart and increment quantity of that item(instead of adding GO TO CART option)

This looks a bit complex but will try to implement it later. For now, I've created an [issue](https://github.com/VishalPatil18/viskart-react-version/issues/30) for the same. Thank you for the suggestion.

**Comment by VishalPatil18** [comment]
> UI looks great now. Sharing functionality is also working perfectly. One thing I would like to suggest about the footer is You can give footer width: 100%. right now it's centered
> 
> image
> ## Reason:
> 
> I checked some sites and noticed that if the footer has color then `width:100% ` and on some sites where footer is transparent (without any bg-color) there it is centered.
> ## footer with color
> 
> On groww they have centered top but footer is full image image
> ## footer ( with no color)
> 
> On gatsby, they have a transparent footer. image
> 
> Apart from that great work @VishalPatil18 👍

Thank you @gadgetfather for pointing it out. I'll fix this

**Pull request merged**
